#server.ssl.key-store=keystore.p12
#server.ssl.key-store-type = PKCS12
#server.ssl.key-store-password=123456
#server.ssl.key-alias=spring
#server.port = 8443
#server.http2.enabled=true

spring:
  profiles: local


hee:
  name: heeName
  age: ${random.int(0,100)}
  fullName: ${hee.name} Kim
  sessionTimeout: "25"
  #서버포트 랜덤값은 0으로 주기